import 'package:firebase_auth/firebase_auth.dart'
    show FirebaseAuth, FirebaseAuthException;
import 'package:firebase_core/firebase_core.dart';
import 'package:my_notes/firebase_options.dart';
import 'package:my_notes/services/auth/auth_exceptions.dart';
import 'package:my_notes/services/auth/auth_provider.dart';
import 'package:my_notes/services/auth/auth_user.dart';

/// Firebase Authentication implementation of [AuthProvider].
///
/// All Firebase-specific error codes are translated into strongly-typed
/// [AuthException] subclasses so that the rest of the app never needs to
/// import `firebase_auth` directly.
class FirebaseAuthProvider implements AuthProvider {
  // ── AuthProvider ───────────────────────────────────────────────────────────

  /// Initialises the Firebase SDK using the platform-specific options
  /// generated by `flutterfire configure`.
  @override
  Future<void> initialize() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }

  /// Returns the currently signed-in user as an [AuthUser], or `null`.
  @override
  AuthUser? get currentUser {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      return AuthUser.fromFirebase(user);
    } else {
      return null;
    }
  }

  /// Creates a new Firebase account and returns the resulting [AuthUser].
  ///
  /// Translates [FirebaseAuthException] codes to the appropriate
  /// [AuthException] subtype.
  @override
  Future<AuthUser> createUser({
    required String email,
    required String password,
  }) async {
    try {
      final userCredential = await FirebaseAuth.instance
          .createUserWithEmailAndPassword(email: email, password: password);
      return AuthUser.fromFirebase(userCredential.user!);
    } on FirebaseAuthException catch (e) {
      if (e.code == 'weak-password') {
        throw WeakPasswordAuthException();
      } else if (e.code == 'email-already-in-use') {
        throw EmailAlreadyInUseAuthException();
      } else if (e.code == 'invalid-email') {
        throw InvalidEmailAuthException();
      } else {
        throw GenericAuthException();
      }
    } catch (e) {
      throw GenericAuthException();
    }
  }

  /// Signs in an existing user and returns the resulting [AuthUser].
  ///
  /// Translates [FirebaseAuthException] codes to the appropriate
  /// [AuthException] subtype.
  @override
  Future<AuthUser> logIn({
    required String email,
    required String password,
  }) async {
    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
      final user = currentUser;

      if (user != null) {
        return user;
      } else {
        throw UserNotFoundAuthException();
      }
    } on FirebaseAuthException catch (e) {
      if (e.code == 'user-not-found') {
        throw UserNotFoundAuthException();
      } else if (e.code == 'wrong-password') {
        throw WrongPasswordAuthException();
      } else if (e.code == 'invalid-email') {
        throw InvalidEmailAuthException();
      } else {
        throw GenericAuthException();
      }
    } catch (e) {
      throw GenericAuthException();
    }
  }

  /// Signs out the current user.
  ///
  /// Throws [UserNotLoggedInAuthException] if no user is signed in.
  @override
  Future<void> logOut() {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      return FirebaseAuth.instance.signOut();
    } else {
      throw UserNotLoggedInAuthException();
    }
  }

  /// Sends a verification email to the current user.
  ///
  /// Throws [UserNotLoggedInAuthException] if no user is signed in.
  @override
  Future<void> sendEmailVerification() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      return user.sendEmailVerification();
    } else {
      throw UserNotLoggedInAuthException();
    }
  }

  /// Sends a password-reset email to [email].
  ///
  /// Throws [UserNotFoundAuthException] for unknown addresses.
  @override
  Future<void> sendPasswordReset({required String email}) async {
    try {
      return FirebaseAuth.instance.sendPasswordResetEmail(email: email);
    } on FirebaseAuthException catch (e) {
      if (e.code == 'user-not-found') {
        throw UserNotFoundAuthException();
      } else if (e.code == 'invalid-email') {
        throw InvalidEmailAuthException();
      } else {
        throw GenericAuthException();
      }
    } catch (e) {
      throw GenericAuthException();
    }
  }

  /// Reloads the current user's profile from Firebase.
  ///
  /// Throws [UserNotLoggedInAuthException] if no user is signed in.
  @override
  Future<void> reloadUser() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      return user.reload();
    } else {
      throw UserNotLoggedInAuthException();
    }
  }
}
