// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BS7ASNjH7GbvcZW3CP4bUcPsEZ3WlYc',
    appId: '1:906864918944:android:e154d2d04c7aeec97464c5',
    messagingSenderId: '906864918944',
    projectId: 'my-notes-23343035',
    storageBucket: 'my-notes-23343035.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv-4jhOwiTC57xxpmAKFAvGXoNY84YiZ8',
    appId: '1:906864918944:ios:c6132b4c264538997464c5',
    messagingSenderId: '906864918944',
    projectId: 'my-notes-23343035',
    storageBucket: 'my-notes-23343035.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChM9XBeAVfyqQTnNfQ_E5fmz0FCn3S0QE',
    appId: '1:906864918944:web:b5ecd6063d759d9b7464c5',
    messagingSenderId: '906864918944',
    projectId: 'my-notes-23343035',
    authDomain: 'my-notes-23343035.firebaseapp.com',
    storageBucket: 'my-notes-23343035.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv-4jhOwiTC57xxpmAKFAvGXoNY84YiZ8',
    appId: '1:906864918944:ios:c6132b4c264538997464c5',
    messagingSenderId: '906864918944',
    projectId: 'my-notes-23343035',
    storageBucket: 'my-notes-23343035.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChM9XBeAVfyqQTnNfQ_E5fmz0FCn3S0QE',
    appId: '1:906864918944:web:80b04211e7ddfddc7464c5',
    messagingSenderId: '906864918944',
    projectId: 'my-notes-23343035',
    authDomain: 'my-notes-23343035.firebaseapp.com',
    storageBucket: 'my-notes-23343035.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyChM9XBeAVfyqQTnNfQ_E5fmz0FCn3S0QE',
    appId: '1:906864918944:web:b5ecd6063d759d9b7464c5',
    messagingSenderId: '906864918944',
    projectId: 'my-notes-23343035',
    authDomain: 'my-notes-23343035.firebaseapp.com',
    storageBucket: 'my-notes-23343035.firebasestorage.app',
  );

}
